config/routes.rb
VirtualGym::Application.routes.draw do

  resources :request_friendships

  resources :challenges

  resources :photo_events

  get "challenges/index"
  get "charts/index"
  get "/profiles/add_friend"
  get "/profiles/index_friend"

  get "/messages/inbox"
  get "/messages/sent"

  get "/workouts/finish_workout"

    authenticated :user do
      resources :profiles
    end
    unauthenticated :user do
      root :to => redirect("users/sign_up")
    end

  resources :workout_plans do
    member do
      get :add_exercise
    end
  end

  resources :exercises do
    collection do
      get :add_exercise
    end
  end

  resources :workout_includings do
    member do
      post :set_fields
    end
  end

  devise_for :users

  resources :charts

  resources :profiles

  resources :messages

  resources :friendships

  resources :amount_types

  resources :equipment

  resources :foods

  resources :exercises

  resources :workouts

  resources :plans

end

app/controllers/amount_types_controller.rb
class AmountTypesController < ApplicationController
  before_action :set_amount_type, only: [:show, :edit, :update, :destroy]
  layout "admin"
  # GET /amount_types
  # GET /amount_types.json
  def index
    @amount_types = AmountType.all
  end

  # GET /amount_types/1
  # GET /amount_types/1.json
  def show
  end

  # GET /amount_types/new
  def new
    @amount_type = AmountType.new
  end

  # GET /amount_types/1/edit
  def edit
  end

  # POST /amount_types
  # POST /amount_types.json
  def create
    @amount_type = AmountType.new(amount_type_params)

    respond_to do |format|
      if @amount_type.save
        format.html { redirect_to @amount_type, notice: 'Amount type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @amount_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @amount_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /amount_types/1
  # PATCH/PUT /amount_types/1.json
  def update
    respond_to do |format|
      if @amount_type.update(amount_type_params)
        format.html { redirect_to @amount_type, notice: 'Amount type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @amount_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /amount_types/1
  # DELETE /amount_types/1.json
  def destroy
    @amount_type.destroy
    respond_to do |format|
      format.html { redirect_to amount_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_amount_type
      @amount_type = AmountType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def amount_type_params
      params.require(:amount_type).permit(:name)
    end
end

app/helpers/amount_types_helper.rb
module AmountTypesHelper
end

app/views/amount_types/_form.html.erb
<%= form_for(@amount_type) do |f| %>
  <% if @amount_type.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(@amount_type.errors.count, "error") %>t ('profile.amounterror'):</h4>

      <ul>
      <% @amount_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t('profile.name') %><br>
    <%= f.text_field :name ,:class => 'form-control'%>
    <br>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/amount_types/edit.html.erb
<h1>t('profile.editamount')</h1>

<%= render 'form' %>

<%= link_to t('profile.show'), @amount_type %> |
<%= link_to t('profile.back'), amount_types_path %>

app/views/amount_types/index.html.erb
<h1>t('profile.listamount')</h1><br>
<%= link_to raw('<span class="glyphicon glyphicon-plus"></span> New'), new_amount_type_path ,:class => "btn btn-info"%><br><br>


<div class="table-responsive">
  <table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @amount_types.each do |amount_type| %>
      <tr>
        <td><%= amount_type.name %></td>
        <td><%= link_to raw('<span class="glyphicon glyphicon-list-alt"></span> Show'), amount_type %></td>
        <td><%= link_to raw('<span class="glyphicon glyphicon-pencil"></span> Edit'), edit_amount_type_path(amount_type) %></td>
        <td><%= link_to raw('<span class="glyphicon glyphicon-remove"></span> Destroy'), amount_type, method: :delete, data: { confirm: t('profile.removequest') } %></td>

      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

app/views/amount_types/new.html.erb
<h1>t('profile.newamount')</h1>

<%= render 'form' %>

<%= link_to 'Back', amount_types_path %>

app/views/amount_types/show.html.erb
<% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %>">
      <%= value %>
    </div>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @amount_type.name %>
</p>

<%= link_to 'Edit', edit_amount_type_path(@amount_type) %> |
<%= link_to 'Back', amount_types_path %>