config/routes.rb
VirtualGym::Application.routes.draw do

  resources :request_friendships

  resources :challenges

  resources :photo_events

  get "challenges/index"
  get "charts/index"
  get "/profiles/add_friend"
  get "/profiles/index_friend"

  get "/messages/inbox"
  get "/messages/sent"

  get "/workouts/finish_workout"

    authenticated :user do
      resources :profiles
    end
    unauthenticated :user do
      root :to => redirect("users/sign_up")
    end

  resources :workout_plans do
    member do
      get :add_exercise
    end
  end

  resources :exercises do
    collection do
      get :add_exercise
    end
  end

  resources :workout_includings do
    member do
      post :set_fields
    end
  end

  devise_for :users

  resources :charts

  resources :profiles

  resources :messages

  resources :friendships

  resources :amount_types

  resources :equipment

  resources :foods

  resources :exercises

  resources :workouts

  resources :plans

end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :amount_type
  has_attached_file :avatar, :styles => { :medium => "200x200#", :thumb => "50x50#" }, :default_url => "/images/:style/Fruit.jpg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def self.search(search)
    if search
      where( 'name LIKE ?  ', "%#{search}%")
    else
      scoped
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  layout "admin"
  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.search(params[:search]).paginate(:page => params[:page], :per_page => 3)
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
    @amount_types = AmountType.order('name ASC')
  end

  # GET /foods/1/edit
  def edit
    @amount_types = AmountType.order('name ASC')
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render action: 'show', status: :created, location: @food }
      else
        @amount_types = AmountType.order('name ASC')
        format.html { render action: 'new' }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { head :no_content }
      else
        @amount_types = AmountType.order('name ASC')
        format.html { render action: 'edit' }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:name, :calory, :protein, :carbohydrate, :fat, :amount_type_id, :per, :avatar)
    end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<%= form_for(@food, :html => { :class => 'form-horizontal' , :role => "form",:multipart => true })   do |f| %>
  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, "error") %> t('profile.food_err')</h2>

      <ul>
      <% @food.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10">
          <div class="form-group">
            <%= f.label :name ,:class => 'col-sm-4 control-label'%>
            <div class="col-sm-8">
                <%= f.text_field :name ,:class => 'form-control ', :placeholder => 'Name'%>
            </div>
          </div>
      </div>
    </div>
    <br>

    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10">
        <div class="form-group">
          <%= f.label t('profile.amount_id'),:class => 'col-sm-4 control-label'%>
          <div class="col-sm-8">
            <%= f.select :amount_type_id , @amount_types.map { |e| [ e.name , e.id ] } ,{}, {:class => 'form-control' } %>
            <%= link_to "manage amount type" , controller: "amount_types" , action: "index"%>
          </div>
        </div>
      </div>
    </div>
    <br>

    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10">
        <div class="form-group">
          <%= f.label t('profile.per') ,:class => 'col-sm-4 control-label'%>
          <div class="col-sm-8">
            <%= f.text_field :per ,:class => 'form-control ' , :placeholder => t('profile.per')%>
          </div>
        </div>
      </div>
    </div>
    <br>

    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10">
          <div class="form-group">
            <%= f.label t('profile.cal') ,:class => 'col-sm-4 control-label'%>
            <div class="col-sm-8">
                <%= f.number_field :calory ,:class => 'form-control ', :placeholder => t('profile.cal')%>
            </div>
          </div>
      </div>
    </div>
    <br>

    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10">
          <div class="form-group">
            <%= f.label t('profile.protein') ,:class => 'col-sm-4 control-label'%>
            <div class="col-sm-8">
                <%= f.text_field :protein  ,:class => 'form-control ', :placeholder => t('profile.protein') %>
            </div>
          </div>
      </div>
    </div>
    <br>

    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10">
          <div class="form-group">
            <%= f.label t('profile.carb') ,:class => 'col-sm-4 control-label'%>
            <div class="col-sm-8">
                <%= f.text_field :carbohydrate ,:class => 'form-control ', :placeholder => t('profile.carb')%>
            </div>
          </div>
      </div>
    </div>
    <br>

    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10">
          <div class="form-group">
            <%= f.label t('profile.fat') ,:class => 'col-sm-4 control-label'%>
            <div class="col-sm-8">
                <%= f.text_field :fat ,:class => 'form-control ' , :placeholder => t('profile.fat')%>
            </div>
          </div>
      </div>
    </div>
    <br>

    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10">
        <div class="form-group">
          <%= f.label t('profile.pic') ,:class => 'col-sm-4 control-label'%>
          <div class="col-sm-8">
            <%= f.file_field :avatar %>
          </div>
        </div>
      </div>
    </div>
    <br>

  <div class="form-group row">
    <!--<button type="submit" class="btn btn-primary"> Let's Go <span class="glyphicon glyphicon-chevron-right"></span></button>-->
    <%= f.submit 'Create' , :class => 'btn btn-info'  %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>t('profile.edit_food')</h1>

<%= render 'form' %>

<%= link_to t 'profile.show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<h1>t('profile.food_list')</h1><br>

<br>
<%= form_tag profiles_path, :method => 'get' , :class => 'form-inline' do %>
    <p>
    <div class="form-group">
      <%= text_field_tag :search, params[:search] ,:class => 'form-control ' ,:placeholder => t('profile.enterplace')%>
    </div>
    <div class="form-group">
      <%= submit_tag t('profile.search'),:class => 'btn btn-primary ', :name => nil %>
    </div>
    </p>
<% end %>

<br>
<br>
<div class="table-responsive ">
  <table class="table table-hover">
  <thead>
    <tr>
      <th>Picture</th>
      <th>Name</th>
      <th>Calory</th>
      <th>Protein</th>
      <th>Carbohydrate</th>
      <th>Fat</th>
      <th>Amount type</th>
      <th>Per</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= image_tag food.avatar.url(:thumb) ,{id: food.id , class: "img-circle img-responsive img-thumbnail" , width: "100" , height: "100" , alt: "Fruit"}%>
        <td><%= food.name %></td>
        <td><%= food.calory %></td>
        <td><%= food.protein %></td>
        <td><%= food.carbohydrate %></td>
        <td><%= food.fat %></td>
        <td><%= food.amount_type.name %></td>
        <td><%= food.per %></td>
        <td><%= link_to raw('<span class="glyphicon glyphicon-list-alt"></span>Show'), food %></td>
        <td><%= link_to raw('<span class="glyphicon glyphicon-pencil"></span>Edit'), edit_food_path(food) %></td>
        <td><%= link_to raw('<span class="glyphicon glyphicon-remove"></span>Destroy'), food, method: :delete, data: { confirm: t('profile.removequest') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  </div>

<br>

<%= link_to raw('<span class="glyphicon glyphicon-plus"></span>'), new_food_path ,:class => "btn btn-primary" , :style => "color: rgb(255,255,255);"%><br><br>
<br>

<%= will_paginate @foods, renderer: BootstrapPagination::Rails %>

app/views/foods/new.html.erb
<h1>t('profile.new_food')</h1>

<%= render 'form' %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %>">
      <%= value %>
    </div>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @food.name %>
</p>

<p>
  <strong>Calory:</strong>
  <%= @food.calory %>
</p>

<p>
  <strong>Protein:</strong>
  <%= @food.protein %>
</p>

<p>
  <strong>Carbohydrate:</strong>
  <%= @food.carbohydrate %>
</p>

<p>
  <strong>Fat:</strong>
  <%= @food.fat %>
</p>

<p>
  <strong>Amount type:</strong>
  <%= @food.amount_type.name %>
</p>

<p>
  <strong>Per:</strong>
  <%= @food.per %>
</p>

<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>