config/routes.rb
VirtualGym::Application.routes.draw do

  resources :request_friendships

  resources :challenges

  resources :photo_events

  get "challenges/index"
  get "charts/index"
  get "/profiles/add_friend"
  get "/profiles/index_friend"

  get "/messages/inbox"
  get "/messages/sent"

  get "/workouts/finish_workout"

    authenticated :user do
      resources :profiles
    end
    unauthenticated :user do
      root :to => redirect("users/sign_up")
    end

  resources :workout_plans do
    member do
      get :add_exercise
    end
  end

  resources :exercises do
    collection do
      get :add_exercise
    end
  end

  resources :workout_includings do
    member do
      post :set_fields
    end
  end

  devise_for :users

  resources :charts

  resources :profiles

  resources :messages

  resources :friendships

  resources :amount_types

  resources :equipment

  resources :foods

  resources :exercises

  resources :workouts

  resources :plans

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_and_belongs_to_many :foods
  has_many :taking_food_plans
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]
  layout "admin"
  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render action: 'show', status: :created, location: @plan }
      else
        format.html { render action: 'new' }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:total_cal, :total_protein, :total_carbohydrate, :total_fat)
    end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= form_for(@plan, :html => { :class => 'form-horizontal' , :role => "form" }) do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> t('profile.plan_err')</h2>

      <ul>
      <% @plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10">
        <div class="form-group">
        <%= f.label t('profile.totalcal') ,:class => 'col-sm-4 control-label'%>
          <div class="col-sm-8">
            <%= f.number_field :total_cal ,:class => 'form-control ', :placeholder => 'Total Calories'%>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10">
        <div class="form-group">
          <%= f.label t('profile.totalprotein') ,:class => 'col-sm-4 control-label'%>
          <div class="col-sm-8">
            <%= f.text_field :total_protein ,:class => 'form-control ', :placeholder => t('profile.totalprotein')%>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10">
        <div class="form-group">
            <%= f.label t('profile.totalcarb') ,:class => 'col-sm-4 control-label' %>
            <div class="col-sm-8">
                <%= f.text_field :total_carbohydrate ,:class => 'form-control ', :placeholder => t('profile.totalcarb')%>
            </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10">
        <div class="form-group">
            <%= f.label t('profile.totalfat') ,:class => 'col-sm-4 control-label' %>
            <div class="col-sm-8">
                <%= f.text_field :total_fat ,:class => 'form-control ' , :placeholder =>t('profile.totalfat')%>
            </div>
        </div>
      </div>
    </div>
    <div class="form-group row">
      <!--<button type="submit" class="btn btn-primary"> Let's Go <span class="glyphicon glyphicon-chevron-right"></span></button>-->
      <%= f.submit t('profile.create') , :class => 'btn btn-info'  %>
    </div>
<% end %>

app/views/plans/edit.html.erb
<h1>t('profile.editplan')</h1>

<%= render 'form' %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<h1>t('profile.listplan')</h1><br>
<%= link_to raw('<span class="glyphicon glyphicon-plus"></span> New'), new_plan_path ,:class => "btn btn-info"%><br><br>


<div class="table-responsive">
  <table class="table table-hover">
  <thead>
    <tr>
      <th>Total cal</th>
      <th>Total protein</th>
      <th>Total carbohydrate</th>
      <th>Total fat</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @plans.each do |plan| %>
      <tr>
        <td><%= plan.total_cal %></td>
        <td><%= plan.total_protein %></td>
        <td><%= plan.total_carbohydrate %></td>
        <td><%= plan.total_fat %></td>
        <td><%= link_to raw('<span class="glyphicon glyphicon-list-alt"></span>Show'), plan %></td>
        <td><%= link_to raw('<span class="glyphicon glyphicon-pencil"></span>Edit'), edit_plan_path(plan) %></td>
        <td><%= link_to raw('<span class="glyphicon glyphicon-remove"></span>Remove'), plan, method: :delete, data: { confirm: t('profile.removequest') } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

</div>

app/views/plans/new.html.erb
<h1>t('profile.newplan')</h1>

<%= render 'form' %>

<%= link_to 'Back', plans_path %>

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Total cal:</strong>
  <%= @plan.total_cal %>
</p>

<p>
  <strong>Total protein:</strong>
  <%= @plan.total_protein %>
</p>

<p>
  <strong>Total carbohydrate:</strong>
  <%= @plan.total_carbohydrate %>
</p>

<p>
  <strong>Total fat:</strong>
  <%= @plan.total_fat %>
</p>

<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>