config/routes.rb
VirtualGym::Application.routes.draw do

  resources :request_friendships

  resources :challenges

  resources :photo_events

  get "challenges/index"
  get "charts/index"
  get "/profiles/add_friend"
  get "/profiles/index_friend"

  get "/messages/inbox"
  get "/messages/sent"

  get "/workouts/finish_workout"

    authenticated :user do
      resources :profiles
    end
    unauthenticated :user do
      root :to => redirect("users/sign_up")
    end

  resources :workout_plans do
    member do
      get :add_exercise
    end
  end

  resources :exercises do
    collection do
      get :add_exercise
    end
  end

  resources :workout_includings do
    member do
      post :set_fields
    end
  end

  devise_for :users

  resources :charts

  resources :profiles

  resources :messages

  resources :friendships

  resources :amount_types

  resources :equipment

  resources :foods

  resources :exercises

  resources :workouts

  resources :plans

end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]
  layout "admin"
  # GET /exercises
  # GET /exercises.json
  def index
    @exercises = Exercise.all.order(:part).order(:level).paginate(:page => params[:page], :per_page => 10)
  end

  # GET /exercises/1
  # GET /exercises/1.json
  def show

  end

  # GET /exercises/new
  def new
    @exercise = Exercise.new
    @equipments = Equipment.order('name ASC')
  end

  # GET /exercises/1/edit
  def edit
    @equipments = Equipment.order('name ASC')
  end

  # POST /exercises
  # POST /exercises.json
  def create
    @exercise = Exercise.new(exercise_params)

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to @exercise, notice: "#{t 'other.create_success'}" }
        format.json { render action: 'show', status: :created, location: @exercise }
      else
        @equipments = Equipment.order('name ASC')
        format.html { render action: 'new' }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercises/1
  # PATCH/PUT /exercises/1.json
  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to @exercise, notice: "#{t 'other.update_success'}" }
        format.json { head :no_content }
      else
        @equipments = Equipment.order('name ASC')
        format.html { render action: 'edit' }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1
  # DELETE /exercises/1.json
  def destroy
    @exercise.destroy
    respond_to do |format|
      format.html { redirect_to exercises_url }
      format.json { head :no_content }
    end
  end


  def add_exercise
    @exercises = Exercise.search(params[:search])
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_exercise
    @exercise = Exercise.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def exercise_params
    params.require(:exercise).permit(:name, :part, :description, :description_fa, :level, :equipment_id, :days_per_week , :video, :avatar,:equipment_name)
  end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_form.html.erb
<%= form_for(@exercise) do |f| %>
  <% if @exercise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercise.errors.count, "error") %> Add Exercise </h2>

      <ul>
      <% @exercise.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <br>
    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10">
        <div class="form-group">
          <%= f.label t'other.name' ,:class => 'col-sm-4 control-label'%><br>
          <%= f.text_field :name ,:class => 'form-control ', :placeholder => 'name'%>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10">
        <div class="form-group">
          <%= f.label t'other.part' ,:class => 'col-sm-4 control-label'%><br>
          <%= f.select :part, [t('other.abss') , t('other.chest') , t('other.backk') , t('other.leg') , t('other.arms')] ,{}, {:class => 'form-control'}%>
        </div>
      </div>
    </div>
    <br>

    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10">
        <div class="form-group">
          <%= f.label  t'other.dpw' ,:class => 'col-sm-4 control-label'%><br>
          <%= f.number_field :days_per_week ,:class => 'form-control '%>
        </div>
      </div>
    </div>

    <br>
    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10">
        <div class="form-group">
          <%= f.label t'other.level' ,:class => 'col-sm-4 control-label'%><br>
          <%= f.select :level, options_for_select([[t('other.basic'),'0'],[t('other.inter'),'1'] , [t('other.diff'),'2']]),{} ,{:class => 'form-control'}%>
          </div>
        </div>
      </div>


    <br>
    <script type="text/javascript">
        $(function() {
            $('#exercise_equipment_name').autocomplete({
                source: $('#exercise_equipment_name').data('autocomplete-source')
            });
        });
    </script>

    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10">
        <div class="form-group">
          <%= f.label t('other.equipment') ,:class => 'col-sm-4 control-label'%>
          <%= f.text_field :equipment_name ,:data => {autocomplete_source: Equipment.order(:name).map(&:name)},:class => 'form-control ', :placeholder => 'Equipment Name' %>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10">
        <div class="form-group">
          <%= f.label t'other.descp' ,:class => 'col-sm-4 control-label'%><br>
          <%= f.text_area :description ,:class => 'form-control ',size: "24x6", :placeholder => 'Description English' %>
         </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10">
        <div class="form-group">
          <%= f.label t'other.descp_fa' ,:class => 'col-sm-4 control-label'%><br>
          <%= f.text_area :description_fa ,:class => 'form-control ',size: "24x6", :placeholder => 'توضیح فارسی'%>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10">
        <div class="form-group">
          <%= f.label t'other.vid_link' ,:class => 'col-sm-4 control-label'%><br>
          <%= f.file_field :video %>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-5 col-sm-5 col-sx-10">
        <div class="form-group">
          <%= f.label t'other.avatar' ,:class => 'col-sm-4 control-label'%><br>
          <%= f.file_field :avatar %>
        </div>
      </div>
    </div>
    <br>
    <br>
    <div class="actions">
      <%= f.submit :class => 'btn btn-primary'%>
    </div>
<% end %>

app/views/exercises/edit.html.erb
<h1><%= t('other.ex_edit')%></h1>

<%= render 'form' %>

<%= link_to t('other.show'), @exercise %> |
<%= link_to t('other.back'), exercises_path %>

app/views/exercises/index.html.erb
<h1><%= t('other.excercise')%> </h1><br>
<%= link_to raw('<span class="glyphicon glyphicon-plus"></span>'), new_exercise_path ,:class => "btn btn-primary" , :style => "color: rgb(255,255,255);"%><br><br>
<br>
<div class="table-responsive">
  <table class="table table-hover">
  <thead>
    <tr>
      <th><%= t'other.avatar'%></th>
      <th><strong><%= t'other.abs'%></strong></th>
      <th><%= t'other.name'%></th>
      <th><%= t'other.level'%></th>
      <th><%= t'other.equipment'%></th>
      <th><%= t'other.dpw'%></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @exercises.each do |exercise| %>
      <tr>
        <td><%= image_tag exercise.avatar.url(:thumb) ,{id: exercise.id , class: "img-circle img-responsive img-thumbnail" , width: "100" , height: "100" , alt: "Exercise"}%>
        <td><strong><%= exercise.part %></strong></td>
        <td><%= exercise.name.capitalize %></td>
        <td>
            <% case exercise.level %>
                <% when 0%>
            <%= t('other.basic') %>
                <% when 1%>
            <%= t('other.inter') %>
                <% when 2%>
            <%= t('other.diff') %>
            <% end%>
        </td>
        <td><%= exercise.equipment.name %></td>
        <td><%= exercise.days_per_week %></td>
        <td><%= link_to raw("<span class='glyphicon glyphicon-list-alt'></span> #{t('other.show')}"), exercise %></td>
        <td><%= link_to raw("<span class='glyphicon glyphicon-pencil'></span> #{t('other.edit')}"), edit_exercise_path(exercise) %></td>
        <td><%= link_to raw("<span class='glyphicon glyphicon-remove'></span> #{t('other.remove')}"), exercise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  </div>

<br>
<%= will_paginate @exercises, renderer: BootstrapPagination::Rails %>

app/views/exercises/new.html.erb
<h1><%= t('other.new_ex')%></h1>

<%= render 'form' %>

<%= link_to t('other.back'), exercises_path %>

app/views/exercises/show.html.erb
<br>
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %>">
      <%= value %>
    </div>
    <br>
  <% end %>

<div class="row">
  <div class="col-md-8  col-sm-8  col-xs-12">


        <%= videojs_rails id:"example_video_1" ,  sources: { mp4: @exercise.video_url}  %>

  </div>
  <div class="col-md-4 col-sm-4 col-xs-12">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><strong><%= t 'other.name' %> : </strong><%= @exercise.name %></h3>
      </div>
      <div class="panel-body">
        <p>
          <strong><%= t('other.type') %></strong>
          <%= @exercise.part %>
        </p>

        <p>
          <strong><%= t('other.descp') %></strong>
          <%= @exercise.description %>
        </p>

        <p>
          <strong><%= t('other.descp_fa') %></strong>
          <%= @exercise.description_fa %>
        </p>

        <p>
          <strong><%= t('other.level')%> :</strong>
          <% case @exercise.level %>
          <% when 0%>
              <%= t('other.basic') %>
          <% when 1%>
              <%= t('other.inter') %>
          <% when 2%>
              <%= t('other.diff') %>
          <% end%>
        </p>

        <p>
          <strong><%= t('other.equipment')%> :</strong>
          <%= @exercise.equipment.name %>
        </p>

        <p>
          <strong><%= t('other.dpw') %> :</strong>
          <%= @exercise.days_per_week %>
        </p>
      </div>



    </div>
  </div>
</div>
  <br>
  <div class="row">

  </div>


<%= link_to t('other.edit'), edit_exercise_path(@exercise) %> |
<%= link_to t('other.back'), exercises_path %>